spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop # Creates schema on startup, drops on shutdown
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
    defer-datasource-initialization: true # Ensures data.sql runs AFTER Hibernate creates schema
