spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true # Log SQL to the console
        format_sql: true # Format the logged SQL
        use_sql_comments: false # Optional: to make logs cleaner
